<?php

// Auto-generated by build-di-cache.php — do NOT edit manually.
// Generated: 2026-03-10 12:02:10

return array (
  'services' => 
  array (
  ),
  'bindings' => 
  array (
  ),
  'providers' => 
  array (
  ),
);
