<?php

// Auto-generated by build-di-cache.php — do NOT edit manually.
// Generated: 2026-03-27 13:09:49

return array (
  'services' => 
  array (
    'BookneticApp\\Backend\\Locations\\Repositories\\LocationCategoryRepository' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Locations\\Repositories\\LocationRepository' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Locations\\Repositories\\LocationAppointmentRepository' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Locations\\Repositories\\LocationStaffRepository' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Locations\\Controllers\\LocationCategoryAjaxController' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Locations\\Controllers\\LocationCategoryController' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Locations\\Controllers\\LocationAjaxController' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Locations\\Controllers\\LocationController' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Locations\\Services\\LocationCategoryService' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Locations\\Services\\LocationService' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Staff\\Repository\\ServiceStaffRepository' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Staff\\Repository\\LocationRepository' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Staff\\Repository\\StaffRepository' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Staff\\Repository\\AppointmentRepository' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Staff\\Services\\StaffRelationService' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Staff\\Services\\StaffService' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Backend\\Staff\\Services\\StaffWpUerService' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Providers\\Services\\CapabilityService' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
    'BookneticApp\\Providers\\Services\\MediaService' => 
    array (
      'lifetime' => 'singleton',
      'factory' => NULL,
    ),
  ),
  'bindings' => 
  array (
  ),
  'providers' => 
  array (
  ),
);
