<?php

// Auto-generated by build-dto-cache.php — do NOT edit manually.
// Generated: 2026-03-27 13:09:49

return array (
  'controllers' => 
  array (
    'BookneticApp\\Backend\\Locations\\Controllers\\LocationRestController' => 
    array (
      'getAll' => 
      array (
        0 => 
        array (
          'name' => 'request',
          'type' => 'BookneticApp\\Backend\\Locations\\DTOs\\Request\\GetAllLocationsRequest',
          'fromRequest' => true,
        ),
      ),
      'enable' => 
      array (
        0 => 
        array (
          'name' => 'request',
          'type' => 'BookneticApp\\Backend\\Locations\\DTOs\\Request\\EnableLocationsRequest',
          'fromRequest' => true,
        ),
      ),
      'disable' => 
      array (
        0 => 
        array (
          'name' => 'request',
          'type' => 'BookneticApp\\Backend\\Locations\\DTOs\\Request\\DisableLocationsRequest',
          'fromRequest' => true,
        ),
      ),
      'create' => 
      array (
        0 => 
        array (
          'name' => 'request',
          'type' => 'BookneticApp\\Backend\\Locations\\DTOs\\Request\\CreateLocationRequest',
          'fromRequest' => true,
        ),
      ),
      'update' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'type' => 'int',
          'fromRequest' => false,
        ),
        1 => 
        array (
          'name' => 'request',
          'type' => 'BookneticApp\\Backend\\Locations\\DTOs\\Request\\UpdateLocationRequest',
          'fromRequest' => true,
        ),
      ),
    ),
    'BookneticApp\\Backend\\Staff\\Controllers\\StaffRestController' => 
    array (
      'getAllActive' => 
      array (
        0 => 
        array (
          'name' => 'request',
          'type' => 'BookneticApp\\Backend\\Staff\\DTOs\\Request\\GetAllStaffRequest',
          'fromRequest' => true,
        ),
      ),
    ),
  ),
  'dtos' => 
  array (
    'BookneticApp\\Backend\\Locations\\DTOs\\Request\\GetAllLocationsRequest' => 
    array (
      'search' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'search',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
    ),
    'BookneticApp\\Backend\\Locations\\DTOs\\Request\\EnableLocationsRequest' => 
    array (
      'ids' => 
      array (
        'type' => 'array',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'ids',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
    ),
    'BookneticApp\\Backend\\Locations\\DTOs\\Request\\DisableLocationsRequest' => 
    array (
      'ids' => 
      array (
        'type' => 'array',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'ids',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
    ),
    'BookneticApp\\Backend\\Locations\\DTOs\\Request\\CreateLocationRequest' => 
    array (
      'name' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => false,
        'mapFrom' => 'name',
        'arrayItemType' => NULL,
        'rules' => 
        array (
          0 => 
          array (
            'type' => 'Required',
            'errorMessage' => '',
          ),
        ),
      ),
      'address' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'address',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'phone' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'phone',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'note' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'note',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'latitude' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'latitude',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'longitude' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'longitude',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'addressComponents' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'address_components',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'categoryId' => 
      array (
        'type' => 'int',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'category_id',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'translations' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'translations',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
    ),
    'BookneticApp\\Backend\\Locations\\DTOs\\Request\\UpdateLocationRequest' => 
    array (
      'name' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => false,
        'mapFrom' => 'name',
        'arrayItemType' => NULL,
        'rules' => 
        array (
          0 => 
          array (
            'type' => 'Required',
            'errorMessage' => '',
          ),
        ),
      ),
      'address' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'address',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'phone' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'phone',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'note' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'note',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'latitude' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'latitude',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'longitude' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'longitude',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'addressComponents' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'address_components',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'categoryId' => 
      array (
        'type' => 'int',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'category_id',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'translations' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'translations',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
    ),
    'BookneticApp\\Backend\\Staff\\DTOs\\Request\\GetAllStaffRequest' => 
    array (
      'search' => 
      array (
        'type' => 'string',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'search',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'location' => 
      array (
        'type' => 'int',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'location',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
      'service' => 
      array (
        'type' => 'int',
        'nullable' => false,
        'hasDefault' => true,
        'mapFrom' => 'service',
        'arrayItemType' => NULL,
        'rules' => 
        array (
        ),
      ),
    ),
  ),
);
