<?php

// Auto-generated by RocketRouter — do not edit.

return array (
  0 => 
  BookneticApp\Providers\Router\RouteItem::__set_state(array(
     'route' => '/locations/',
     'method' => 'GET',
     'controller' => 'BookneticApp\\Backend\\Locations\\Controllers\\LocationRestController',
     'action' => 'getAll',
     'params' => 
    array (
      0 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'request',
         'type' => 'BookneticApp\\Backend\\Locations\\DTOs\\Request\\GetAllLocationsRequest',
         'source' => 'query',
         'alias' => NULL,
         'isOptional' => false,
         'default' => NULL,
      )),
    ),
  )),
  1 => 
  BookneticApp\Providers\Router\RouteItem::__set_state(array(
     'route' => '/locations/enable',
     'method' => 'POST',
     'controller' => 'BookneticApp\\Backend\\Locations\\Controllers\\LocationRestController',
     'action' => 'enable',
     'params' => 
    array (
      0 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'request',
         'type' => 'BookneticApp\\Backend\\Locations\\DTOs\\Request\\EnableLocationsRequest',
         'source' => 'body',
         'alias' => NULL,
         'isOptional' => false,
         'default' => NULL,
      )),
    ),
  )),
  2 => 
  BookneticApp\Providers\Router\RouteItem::__set_state(array(
     'route' => '/locations/disable',
     'method' => 'POST',
     'controller' => 'BookneticApp\\Backend\\Locations\\Controllers\\LocationRestController',
     'action' => 'disable',
     'params' => 
    array (
      0 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'request',
         'type' => 'BookneticApp\\Backend\\Locations\\DTOs\\Request\\DisableLocationsRequest',
         'source' => 'body',
         'alias' => NULL,
         'isOptional' => false,
         'default' => NULL,
      )),
    ),
  )),
  3 => 
  BookneticApp\Providers\Router\RouteItem::__set_state(array(
     'route' => '/locations/{id}',
     'method' => 'GET',
     'controller' => 'BookneticApp\\Backend\\Locations\\Controllers\\LocationRestController',
     'action' => 'get',
     'params' => 
    array (
      0 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'id',
         'type' => 'int',
         'source' => 'route',
         'alias' => 'id',
         'isOptional' => false,
         'default' => NULL,
      )),
    ),
  )),
  4 => 
  BookneticApp\Providers\Router\RouteItem::__set_state(array(
     'route' => '/locations/',
     'method' => 'POST',
     'controller' => 'BookneticApp\\Backend\\Locations\\Controllers\\LocationRestController',
     'action' => 'create',
     'params' => 
    array (
      0 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'request',
         'type' => 'BookneticApp\\Backend\\Locations\\DTOs\\Request\\CreateLocationRequest',
         'source' => 'body',
         'alias' => NULL,
         'isOptional' => false,
         'default' => NULL,
      )),
    ),
  )),
  5 => 
  BookneticApp\Providers\Router\RouteItem::__set_state(array(
     'route' => '/locations/{id}',
     'method' => 'PUT',
     'controller' => 'BookneticApp\\Backend\\Locations\\Controllers\\LocationRestController',
     'action' => 'update',
     'params' => 
    array (
      0 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'id',
         'type' => 'int',
         'source' => 'route',
         'alias' => 'id',
         'isOptional' => false,
         'default' => NULL,
      )),
      1 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'request',
         'type' => 'BookneticApp\\Backend\\Locations\\DTOs\\Request\\UpdateLocationRequest',
         'source' => 'body',
         'alias' => NULL,
         'isOptional' => false,
         'default' => NULL,
      )),
    ),
  )),
  6 => 
  BookneticApp\Providers\Router\RouteItem::__set_state(array(
     'route' => '/locations/{id}/image',
     'method' => 'POST',
     'controller' => 'BookneticApp\\Backend\\Locations\\Controllers\\LocationRestController',
     'action' => 'uploadImage',
     'params' => 
    array (
      0 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'id',
         'type' => 'int',
         'source' => 'route',
         'alias' => 'id',
         'isOptional' => false,
         'default' => NULL,
      )),
      1 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'image',
         'type' => 'array',
         'source' => 'form',
         'alias' => 'image',
         'isOptional' => true,
         'default' => 
        array (
        ),
      )),
    ),
  )),
  7 => 
  BookneticApp\Providers\Router\RouteItem::__set_state(array(
     'route' => '/locations/{id}/toggle-visibility',
     'method' => 'POST',
     'controller' => 'BookneticApp\\Backend\\Locations\\Controllers\\LocationRestController',
     'action' => 'toggleVisibility',
     'params' => 
    array (
      0 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'id',
         'type' => 'int',
         'source' => 'route',
         'alias' => 'id',
         'isOptional' => false,
         'default' => NULL,
      )),
    ),
  )),
  8 => 
  BookneticApp\Providers\Router\RouteItem::__set_state(array(
     'route' => '/locations/{id}',
     'method' => 'DELETE',
     'controller' => 'BookneticApp\\Backend\\Locations\\Controllers\\LocationRestController',
     'action' => 'delete',
     'params' => 
    array (
      0 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'id',
         'type' => 'int',
         'source' => 'route',
         'alias' => 'id',
         'isOptional' => false,
         'default' => NULL,
      )),
    ),
  )),
  9 => 
  BookneticApp\Providers\Router\RouteItem::__set_state(array(
     'route' => '/staffs/',
     'method' => 'GET',
     'controller' => 'BookneticApp\\Backend\\Staff\\Controllers\\StaffRestController',
     'action' => 'getAllActive',
     'params' => 
    array (
      0 => 
      BookneticApp\Providers\Router\RouteParam::__set_state(array(
         'name' => 'request',
         'type' => 'BookneticApp\\Backend\\Staff\\DTOs\\Request\\GetAllStaffRequest',
         'source' => 'query',
         'alias' => NULL,
         'isOptional' => false,
         'default' => NULL,
      )),
    ),
  )),
);
